✨ Feat: 어빌리티 정보 구현(RD-41)
raindropstudio/lara-backend pull request #4
Opened 2024-07-26 19:42 UTC by Decomori

## 어빌리티 기능 구현 내용
- NXAPI에서 오는 내용에 현재 적용중인 어빌리티가 몇 번째 프리셋인지 알려주긴 했음. 하지만 내용은 중복되기 때문에 적용중인 어빌리티 내용은 포함시키지 않고 프리셋에 ```active``` 값으로 표현.
- 남은 명성치 값은 따로 저장

2024-07-27 08:34 UTC, qilip requested changes

2024-07-27 08:34 UTC, qilip commented on prisma/schema.prisma
> +  remainFame   Int?
remainFame 다른 스탯처럼 별도로 빼는게?
아니면 어차피 어빌리티는 3개 확정이니까 ability 123으로 한번에 하는거도 방법일거같은

2024-07-28 20:02 UTC, Decomori commented on prisma/schema.prisma
> +  remainFame   Int?
해당 내용 반영 완료했습니다.

2024-07-28 20:04 UTC, qilip commented on src/character/type/character-ability.type.ts
> +  remainFame?: number;
왜 옵?셔널? 위에꺼만 볼땐 없어지는게 맞지 않나..?

2024-07-28 20:08 UTC, Decomori commented on src/character/type/character-ability.type.ts
> +  remainFame?: number;
죄송합니다 졸았습니다.. 정상화 완료

2024-07-28 20:10 UTC, qilip approved these changes
정상화의 신

사실 저렇게 억지로 넣는게 쿼리때릴때 어떨지 좀 긴가민가하긴 한데 일단 작동하니 조아쓰!!

2024-07-29 06:07 UTC, merged